version: "3.8"

services:
  test: &default
    image: node:12
    working_dir: /app/
    command: "yarn test"
    environment:
      - APP_PORT=3333
      - APP_SECRET=e82b99be76d50e7725045465ae11c80a
      - WEB_DOMAIN=http://localhost:3000
    volumes:
      - .:/app

  install:
    <<: *default
    command: "yarn"

  app: &app
    <<: *default
    command: "yarn dev:server"
    ports:
      - 3333:3333
      - 9229:9229
    depends_on:
      - database
      - mongodb

  database:
    container_name: gostack_postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gostack_gobarber
    ports:
     - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  mongodb:
    container_name: gostack_mongodb
    image: mongo
    ports:
     - 27017:27017
    volumes:
      - mongodata:/data/db

  migrations:
    <<: *app
    command: "yarn typeorm migration:run"

  revert:
    <<: *app
    command: "yarn typeorm migration:revert"

volumes:
  db: {}
  mongodata: {}
