version: "3.7"

services:
  test:
    image: node:12
    working_dir: /app/
    command: "yarn test"
    volumes:
      - .:/app

  install:
    image: node:12
    working_dir: /app/
    command: "yarn"
    volumes:
      - .:/app

  app: &app
    image: node:12
    working_dir: /app/
    command: "yarn dev:server"
    environment:
      - APP_PORT=3333
    volumes:
      - .:/app
    ports:
      - 3333:3333
      - 9229:9229
    depends_on:
      - database

  database:
    container_name: gostack_postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gostack_gobarber
    ports:
     - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  migrations:
    <<: *app
    command: "yarn typeorm migration:run"

  revert:
    <<: *app
    command: "yarn typeorm migration:revert"

volumes:
  db: {}
